"""Hand-crafted GameVault catalog. Not sourced from a public games API."""

GAMES = [
    {
        "title": "Hades",
        "year": 2020,
        "genre": "Roguelike",
        "platform": "PC",
        "developer": "Supergiant Games",
        "rating": 9.3,
        "description": "Escape the Underworld as Zagreus in fast, story-rich runs.",
    },
    {
        "title": "Celeste",
        "year": 2018,
        "genre": "Platformer",
        "platform": "Nintendo Switch",
        "developer": "Maddy Makes Games",
        "rating": 9.1,
        "description": "A precise mountain climb about anxiety, grit, and self-acceptance.",
    },
    {
        "title": "The Witcher 3: Wild Hunt",
        "year": 2015,
        "genre": "Action RPG",
        "platform": "PC",
        "developer": "CD Projekt Red",
        "rating": 9.4,
        "description": "Geralt hunts monsters and makes hard choices across a huge open world.",
    },
    {
        "title": "Stardew Valley",
        "year": 2016,
        "genre": "Simulation",
        "platform": "PC",
        "developer": "ConcernedApe",
        "rating": 9.0,
        "description": "Inherit a farm, befriend townsfolk, and rebuild a quiet valley life.",
    },
    {
        "title": "Elden Ring",
        "year": 2022,
        "genre": "Action RPG",
        "platform": "PlayStation 5",
        "developer": "FromSoftware",
        "rating": 9.6,
        "description": "Explore the Lands Between and survive punishing, open-ended combat.",
    },
    {
        "title": "Hollow Knight",
        "year": 2017,
        "genre": "Metroidvania",
        "platform": "PC",
        "developer": "Team Cherry",
        "rating": 9.2,
        "description": "A lone bug maps a ruined kingdom of insects, secrets, and bosses.",
    },
    {
        "title": "Portal 2",
        "year": 2011,
        "genre": "Puzzle",
        "platform": "PC",
        "developer": "Valve",
        "rating": 9.5,
        "description": "Bend space with portals while GLaDOS and Wheatley trade insults.",
    },
    {
        "title": "Disco Elysium",
        "year": 2019,
        "genre": "RPG",
        "platform": "PC",
        "developer": "ZA/UM",
        "rating": 9.2,
        "description": "A detective RPG where skills argue in your head as you solve a murder.",
    },
    {
        "title": "Animal Crossing: New Horizons",
        "year": 2020,
        "genre": "Simulation",
        "platform": "Nintendo Switch",
        "developer": "Nintendo",
        "rating": 8.6,
        "description": "Build an island town on your own schedule with villagers and DIY crafts.",
    },
    {
        "title": "Super Mario Odyssey",
        "year": 2017,
        "genre": "Platformer",
        "platform": "Nintendo Switch",
        "developer": "Nintendo",
        "rating": 9.7,
        "description": "Mario and Cappy hop across kingdoms collecting Power Moons.",
    },
    {
        "title": "God of War",
        "year": 2018,
        "genre": "Action",
        "platform": "PlayStation 4",
        "developer": "Santa Monica Studio",
        "rating": 9.4,
        "description": "Kratos and Atreus travel Norse realms in a tightly directed combat epic.",
    },
    {
        "title": "Minecraft",
        "year": 2011,
        "genre": "Sandbox",
        "platform": "PC",
        "developer": "Mojang Studios",
        "rating": 9.0,
        "description": "Mine, craft, and build anything in a blocky world that never ends.",
    },
    {
        "title": "Balatro",
        "year": 2024,
        "genre": "Roguelike",
        "platform": "PC",
        "developer": "LocalThunk",
        "rating": 9.1,
        "description": "A poker roguelike that turns jokers and hands into runaway combos.",
    },
    {
        "title": "Persona 5 Royal",
        "year": 2019,
        "genre": "JRPG",
        "platform": "PlayStation 4",
        "developer": "Atlus",
        "rating": 9.5,
        "description": "High school thieves steal hearts by day and raid palaces by night.",
    },
    {
        "title": "Slay the Spire",
        "year": 2019,
        "genre": "Deckbuilder",
        "platform": "PC",
        "developer": "Mega Crit",
        "rating": 9.0,
        "description": "Climb a spire one deck-building fight at a time.",
    },
    {
        "title": "Outer Wilds",
        "year": 2019,
        "genre": "Adventure",
        "platform": "PC",
        "developer": "Mobius Digital",
        "rating": 9.3,
        "description": "Pilot a tiny ship through a solar system that resets every 22 minutes.",
    },
]
